appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: RYzi815u5byY0u/AHn5+CORU8BE49B3Z4e92C3fOflp6lhZ0MpodKfXt1FKKHDTU5KifWPHKqd8ok0EH1bnrHVpu5U/O7fT8iOHd5b5LwJhNvMj05NitRh8F4v87lP2EA6JW2pZGW8QJs6cEdWu6fujha+AUvpDIK8SssQG7dSc2UhI86KEewgO8AdOHqXmwLAMV6E4LinWdu5ET36ELmDfVGF2bAXdyMQawLiFHclgp+lwnTscM+4Uqo9Wr2AyA1MrpejA/Iez9yK2KzqcQVvUsu1tohjEKd3j7uYz0M1NFPs7Mnsmdd4l6UIzwk5BhfrNt2xnVDCCcmizdyJErPgfneH3DbKzo/pzUzC3hCdv9G6AMqLoZNmgm52GWWR+HqxhXuaRun7rW2D6tkv6ewa7BjB90JdexuuOvX2HfGiSzfl+obGlB3IyL6XQg4Fbpk2776g6mfwJ5KCRqRv4nlm/688CCvDD52lQurHc5PdQVrKwlJT+mWnos3EK3u8aUQGZZjSqs3WxvCw8Cj91IpzxDBBULt8I2vjxb+4kZc6wWXW0pliUtbBIz6xq3IUVPrHDN/J9sz4XcgNpiAist71bZPCCFISFqLUNwG4by2mU9P96n2f5iS6Low6JMe1egb2iAgnObvTrLNPhqzUSNCoGXCFXq9MoBZrPS4GzUeiE=
